# Model prediction {#sec-modelprediction}

A species distribution model trained on one set of environmental variables can be projected onto future climate scenarios to forecast potential shifts in habitat suitability over time. Similarly, models based on a species' native distribution can help predict its potential range in new areas outside its current habitat. This approach is valuable for assessing the potential risk of species becoming invasive in new regions.

In this section, we’ll use the model developed in @sec-4trainthemodel to project the future potential distribution of the Almond-eyed Ringlet (*Erebia albergana*) for the period 2081-2100. This projection will use the Shared Socio-economic Pathway (SSP) 585 climate scenario from the *EC-Earth3-Veg* general circulation model.

## Predicting

We already downloaded the climate layers for the above-mentioned SSP and GCM in @sec-obtainfutureclimatelayers, and saved them in the mapset [climate_EC_Earth3_Veg]{.style-db}. Let's first make sure we have access to this mapset from the current mapset. As you might remember, we can use the [g.mapsets](https://grass.osgeo.org/grass-stable/manuals/g.mapsets.html) module for that.

::: {#exm-HXKf6KsqSt .hiddendiv}
:::

::: {.panel-tabset group="interface"}
## {{< fa solid terminal >}}

``` bash
g.mapsets mapset=climate_EC_Earth3_Veg operation=add
```

## {{< fa brands python >}}

``` python
gs.run_command(
    "g.mapsets", mapset=["climate_EC_Earth3_Veg"], operation="add"
)
```

## {{< fa regular window-restore >}}

In the menu, go to [Settings → GRASS working environment → Mapset access]{.style-menu} and select the mapsets [climate_EC_Earth3_Veg]{.style-db}.
:::

We can now use the [r.maxent.predict](https://grass.osgeo.org/grass-stable/manuals/addons/r.maxent.predict.html) to apply the previously created Maxent model to this set of climate raster data. The minimum input requirements are a [lambdas]{.style-output} file, which has the extension *.lambdas*, describing a Maxent model, and the name of the raster layers for the predictor variables described in the lambdas file. The [lambdas]{.style-output} file was one of the outputs from [r.maxent.predict]{.style-function} and can be found in the output folder [model_01]{.style-output}. And we just exported the required input raster layers to the folder [future_climate01]{.style-db} in our working directory. Note, if

For convenience, r.maxent.train creates a file maxent_explanatory_variable_names.csv, which you can check for the names of the predictor variables. If these are different from the input raster layers, you can provide the variable names using the variables parameter. Alternatively, you can provide a CSV file with the names of the explanatory variables (first column) and the names of the corresponding raster layers (second column).

::: {#exm-CZnP5gebFx .hiddendiv}
:::

::: {.panel-tabset group="interface"}
## {{< fa solid terminal >}}

``` bash
# Create a new folder in the working directory
mkdir future_climate01

# Export the Maxent input data
v.maxent.swd \
  evp_maps=bio.1,bio.2,bio.4,bio.8,bio.9,bio.13,bio.14,bio.15 \
  alias_names=bio_1,bio_2,bio_4,bio_8,bio_9,bio_13,bio_14,bio_15 \
  export_rasters=future_climate01
```

## {{< fa brands python >}}

``` python
# Create a new folder in the working directory
os.mkdir("future_climate01")

# Export the Maxent input data
gs.run_command(
    "v.maxent.swd",
    evp_maps="bio.1,bio.2,bio.4,bio.8,bio.9,bio.13,bio.14,bio.15",
    alias_names="bio_1,bio_2,bio_4,bio_8,bio_9,bio_13,bio_14,bio_15",
    export_rasters="dataset01/envdat",
)
```

## {{< fa regular window-restore >}}

Create the folder [future_climate01]{.style-db} using your favorite file browser. Next, open the [v.maxent.swd]{.style-function} dialog and run it with the following parameter settings:

| Parameter      | Value                                              |
|----------------|----------------------------------------------------|
| evp_maps       | bio.1,bio.2,bio.4,bio.8,bio.9,bio.13,bio.14,bio.15 |
| alias_names    | bio_1,bio_2,bio_4,bio_8,bio_9,bio_13,bio_14,bio_15 |
| export_rasters | dataset01/envdat                                   |

: {tbl-colwidths="\[50,50\]"}
:::
