# Sample data {#sec-sampledata}

<br>

### Data in this tutorial {.unnumbered}

The table below provides an overview of the data used in this tutorial.

| Section | Name + link | Type |
|----|----|----|
| @sec-nationalboundaries | [1:10m Admin 0 - Countries](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) | vector |
| @sec-urban | [urban areas](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-urban-area/) | vector |
| @sec-roads | [roads](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/roads/) | vector |
| @sec-rivers | [rivers and lake centerlines](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/) | vector |
| @sec-rivers | [rivers, Europe supplement](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/) | vector |
| @sec-rangemap | [Rangemap Erebia albergana](https://www.iucnredlist.org/search?query=Erebia%20albergana&searchType=species) | vector |
| @sec-occurrence | [GBIF *Erebia alberganus* occurrence data](https://www.gbif.org/species/5134543) | vector |
| @sec-climatedata | [Worldclim historical climate data](https://www.worldclim.org/data/worldclim21.html#) | raster |
| @sec-obtainfutureclimatelayers | [Worldclim future climate data](https://www.worldclim.org/data/cmip6/cmip6climate.html) | raster |

: {tbl-colwidths="\[20,60,20\]"}

<br>

### Other data sources {.unnumbered}

The list below provide a few potentially useful data sources. For a much longer list of curated list of public data sets, see [this link](https://github.com/awesomedata/awesome-public-datasets).

| Variable | Name + link |
|----|----|
| Altitude | [EU DEM](https://ec.europa.eu/eurostat/web/gisco/geodata/digital-elevation-model/eu-dem#DD) |
| Climate data | [ClimateEU: historical and projected climate data for Europe](https://sites.ualberta.ca/~ahamann/data/climateeu.html) |
| Climate data | [Statistical Downscaling (Climgen)](https://www.ccafs-climate.org/statistical_downscaling_climgen/) |
| Climate data | [The ECLIPS-2.0 dataset, High-resolution gridded climate data for Europe](https://zenodo.org/records/3952159) |
| Climate data | [Are there better climate data than Worldclim for Europe?](https://gis.stackexchange.com/questions/82186/are-there-better-climate-data-than-worldclim-for-europe) |
| Climate data | [Climate Data Store](https://cds.climate.copernicus.eu/datasets) |
| Land cover and use | [CORINE Land cover](https://land.copernicus.eu/en/products/corine-land-cover) |
| Land cover and use | [Landelijk grondgebruik Nederland](https://lgn.nl/) |

: {tbl-colwidths="\[30,70\]"}
